apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-api
  template:
    metadata:
      labels:
        app: fiap-api
    spec:
      containers:
        - name: fiap-api
          image: fiap-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:8080
---
apiVersion: v1
kind: Service
metadata:
  name: fiap-api
spec:
  type: NodePort
  selector:
    app: fiap-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
